<?php

return [
    'roles' => [
        'Property Manager' => [
            'permissions' => [
                // 'view_access::card::forms::document',
                // 'view_any_access::card::forms::document',
                // 'create_access::card::forms::document',
                // 'update_access::card::forms::document',
                'view_announcement',
                'view_any_announcement',
                'create_announcement',
                'update_announcement',
                'view_building::building',
                'view_any_building::building',
                'create_building::building',
                'update_building::building',
                // 'view_building::facility::booking',
                // 'view_any_building::facility::booking',
                // 'create_building::facility::booking',
                // 'update_building::facility::booking',
                'view_building::flat',
                'view_any_building::flat',
                'create_building::flat',
                'update_building::flat',
                'view_building::flat::tenant',
                'view_any_building::flat::tenant',
                // 'create_building::flat::tenant',
                'update_building::flat::tenant',
                // 'view_building::service::booking',
                // 'view_any_building::service::booking',
                // 'create_building::service::booking',
                // 'update_building::service::booking',
                // 'view_contract',
                // 'view_any_contract',
                // 'create_contract',
                // 'update_contract',
                'view_cooling::account',
                'view_any_cooling::account',
                'create_cooling::account',
                'update_cooling::account',
                // 'view_fit::out::forms::document',
                // 'view_any_fit::out::forms::document',
                // 'create_fit::out::forms::document',
                // 'update_fit::out::forms::document',
                // 'view_guest::registration',
                // 'view_any_guest::registration',
                // 'create_guest::registration',
                // 'update_guest::registration',
                // 'view_helpdeskcomplaint',
                // 'view_any_helpdeskcomplaint',
                // 'create_helpdeskcomplaint',
                // 'update_helpdeskcomplaint',
                // 'view_invoice',
                // 'view_any_invoice',
                // 'create_invoice',
                // 'update_invoice',
                'view_master::facility',
                'view_any_master::facility',
                'create_master::facility',
                'update_master::facility',
                'view_master::service',
                'view_any_master::service',
                'create_master::service',
                'update_master::service',
                // 'view_mollak::tenant',
                // 'view_any_mollak::tenant',
                // 'create_mollak::tenant',
                // 'update_mollak::tenant',
                // 'view_move::in::forms::document',
                // 'view_any_move::in::forms::document',
                // 'create_move::in::forms::document',
                // 'update_move::in::forms::document',
                // 'view_move::out::forms::document',
                // 'view_any_move::out::forms::document',
                // 'create_move::out::forms::document',
                // 'update_move::out::forms::document',
                // 'view_noc::form',
                // 'view_any_noc::form',
                // 'create_noc::form',
                // 'update_noc::form',
                // 'view_patrolling',
                // 'view_any_patrolling',
                // 'create_patrolling',
                // 'update_patrolling',
                'view_post',
                'view_any_post',
                'create_post',
                'update_post',
                // 'view_proposal',
                // 'view_any_proposal',
                // 'create_proposal',
                // 'update_proposal',
                // 'view_snags',
                // 'view_any_snags',
                // 'create_snags',
                // 'update_snags',
                'view_tenant::document',
                'view_any_tenant::document',
                'create_tenant::document',
                'update_tenant::document',
                // 'view_tender',
                // 'view_any_tender',
                // 'create_tender',
                // 'update_tender',
                'view_user::approval',
                'view_any_user::approval',
                // 'create_user::approval',
                'update_user::approval',
                // 'view_user::owner',
                // 'view_any_user::owner',
                // 'create_user::owner',
                // 'update_user::owner',
                // 'view_user::tenant',
                // 'view_any_user::tenant',
                // 'create_user::tenant',
                // 'update_user::tenant',
                'view_user::user',
                'view_any_user::user',
                'create_user::user',
                'update_user::user',
                // 'view_vehicle',
                // 'view_any_vehicle',
                // 'create_vehicle',
                // 'update_vehicle',
                // 'view_vendor::ledgers',
                // 'view_any_vendor::ledgers',
                // 'create_vendor::ledgers',
                // 'update_vendor::ledgers',
                'view_vendor::vendor',
                'view_any_vendor::vendor',
                'create_vendor::vendor',
                'update_vendor::vendor',
                // 'view_visitor::form',
                // 'view_any_visitor::form',
                // 'create_visitor::form',
                // 'update_visitor::form',
                // 'view_w::d::a',
                // 'view_any_w::d::a',
                // 'create_w::d::a',
                // 'update_w::d::a',
                // 'view_family::member',
                // 'view_any_family::member',
                // 'create_family::member',
                // 'update_family::member',
                // 'view_incident',
                // 'view_any_incident',
                // 'create_incident',
                // 'update_incident',
                // 'view_app::feedback',
                // 'view_any_app::feedback',
                // 'create_app::feedback',
                // 'update_app::feedback',
                'view_property::manager',
                'view_any_property::manager',
                'create_property::manager',
                'update_property::manager',
                'widget_StatsOverview',
                'widget_SecuritesOverview',
                'widget_OwnerTenantRegistrationChart',
                'widget_VendorChart',
                'widget_ComplaintsChart',
                'widget_ComplaintCategoriesChart',
                'widget_WdaChart',
                'widget_RecentOpenComplaints',
                'widget_RecentPendingResidentApprovals',
                'view_shield::role',
                'view_any_shield::role',
                'create_shield::role',
                'update_shield::role',
                'delete_shield::role',
                'delete_any_shield::role',

                'view_any_owner::association::invoice',
                'view_owner::association::invoice',
                'create_owner::association::invoice',
                'update_owner::association::invoice',
                'view_any_owner::association::receipt',
                'view_owner::association::receipt',
                'create_owner::association::receipt',
                'update_owner::association::receipt',
            ],
        ],
    ],
];
